name: yoven
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter


  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  shared_preferences: ^2.0.5
  google_fonts: ^4.0.4


  # Icons
  material_design_icons_flutter: 5.0.6996
  flutter_feather_icons: ^2.0.0+1
  lucide_icons: ^0.257.0

  #(Syncfusion Flutter packages - Charts, Calendar, ETC.)
  syncfusion_flutter_core: ^20.1.56
  syncfusion_flutter_calendar: ^20.1.56
  syncfusion_flutter_datepicker: ^20.1.56
  syncfusion_flutter_sliders: ^20.1.56
  syncfusion_flutter_charts: ^20.1.56
  syncfusion_flutter_gauges: ^20.1.56

  # Other
  google_maps_flutter: ^2.0.3
  shimmer: ^2.0.0
  url_launcher: ^6.0.3
  intl: ^0.18.0
  rive: ^0.8.1
  flare_flutter: ^3.0.2
  flutter_intro: ^2.3.1
  image_picker: ^1.0.2
  #  flutx:
  #    path: ../flutx
  boxicons: ^2.1.3
  #  flutx: ^0.2.0-rc.2
  get: ^4.6.5
  curved_navigation_bar: ^1.0.3
  flashy_tab_bar2: ^0.0.6
  blur: ^3.1.0
#  google_mobile_ads: ^3.0.0
  flutter_blurhash: ^0.7.0
#  flutx: ^0.2.0-rc.1
#  flutx: ^0.1.2

#module:
#  androidX: true

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:

    # Map Styles
    - assets/map/

    # Profiles
    - assets/images/profile/

    # Shopping
    - assets/images/apps/shopping/
    - assets/images/apps/shopping/product/
    - assets/images/apps/shopping/offer/
    - assets/images/apps/shopping/camera/
    - assets/images/apps/shopping/vector/

    # Shopping2
    - assets/images/apps/shopping2/icons/
    - assets/images/apps/shopping2/images/

    # Brand
    - assets/brand/

    # Hotel
    - assets/images/apps/hotel/

    # Places
    - assets/images/place/

    # Music
    - assets/images/apps/music/

    # Food
    - assets/images/apps/food/

    # Estate
    - assets/images/apps/estate/

    # Course
    - assets/images/apps/course/

    # Chat
    - assets/images/apps/chat/

    # Social
    - assets/images/apps/social/

    # Other
    - assets/images/all/

    # Event
    - assets/images/apps/event/

    # Avatars
    - assets/images/profile/

    ###################---------------------- Full Apps -------------------------#################

    ## Animations

    # Shopping
    # Shopping Manager
    - assets/full_apps/animations/shopping/data/
    - assets/images/full_apps/shopping/
    - assets/images/full_apps/shopping/icons/
    - assets/full_apps/animations/shopping_manager/data/

    # Rental Service
    - assets/full_apps/animations/rental_service/data/
    - assets/images/full_apps/rental_service/images/
    - assets/images/full_apps/rental_service/icons/

    # NFT
    - assets/full_apps/animations/nft/data/
    - assets/images/full_apps/nft/images/
    - assets/images/full_apps/nft/icons/


    ## m3

    # Cookify
    - assets/full_apps/m3/cookify/data/

    # Dating
    - assets/full_apps/m3/dating/data/

    # Estate
    - assets/full_apps/m3/estate/data/

    # HomeMade
    - assets/full_apps/m3/homemade/data/

    # Learning
    - assets/full_apps/m3/learning/data/

    # Plant
    - assets/images/full_apps/plant/images/
    - assets/full_apps/animations/plant/data/



    ## Other

    # Dating
    - assets/full_apps/others/dating/data/

    # Fitness
    - assets/images/apps/fitness/images/
    - assets/full_apps/others/fitness/data/

    # HomeMade
    - assets/full_apps/others/homemade/data/

    # Muvi
    - assets/full_apps/others/muvi/data/


    ###################---------------------- Custom Apps -------------------------#################

    # Grocery
    - assets/images/apps/grocery/


    # Homemade
    - assets/images/apps/homemade/
    - assets/images/apps/homemade/products/
    - assets/images/apps/homemade/category/
    - assets/images/apps/homemade/shop/

    # Dating
    - assets/images/apps/dating/

    # Muvi
    - assets/images/apps/muvi/

    # CustomApps
    - assets/images/apps/cookify/
    - assets/images/apps/grocery/
    - assets/images/apps/medicare/

    # Learning  (Material Design 3)
    - assets/images/apps/learning/images/
    - assets/images/apps/learning/icons/

    # Illustration
    - assets/illustration/food/
    - assets/illustration/shopping/
    - assets/illustration/hotel/
    - assets/illustration/music/

    # Month backgrounds
    - assets/images/month_background/

    # Languages
    - assets/lang/

    # Icons
    - assets/icons/

    # Rive Animations
    - assets/animations/rive/

    # Other
    - assets/other/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages