name: yoven
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter


  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  shared_preferences: ^2.0.5
  google_fonts: ^4.0.4


  # Icons
  material_design_icons_flutter: 5.0.6996
  flutter_feather_icons: ^2.0.0+1
  lucide_icons: ^0.257.0

  #(Syncfusion Flutter packages - Charts, Calendar, ETC.)
  syncfusion_flutter_core: ^20.1.56
  syncfusion_flutter_calendar: ^20.1.56
  syncfusion_flutter_datepicker: ^20.1.56
  syncfusion_flutter_sliders: ^20.1.56
  syncfusion_flutter_charts: ^20.1.56
  syncfusion_flutter_gauges: ^20.1.56

  # Other
  google_maps_flutter: ^2.0.3
  shimmer: ^2.0.0
  url_launcher: ^6.0.3
  intl: ^0.18.0
  rive: ^0.8.1
  flare_flutter: ^3.0.2
  flutter_intro: ^2.3.1
  image_picker: ^1.0.2
  #  flutx:
  #    path: ../flutx
  boxicons: ^2.1.3
  #  flutx: ^0.2.0-rc.2
  get: ^4.6.5
  curved_navigation_bar: ^1.0.3
  flashy_tab_bar2: ^0.0.6
  blur: ^3.1.0
#  google_mobile_ads: ^3.0.0
  flutter_blurhash: ^0.7.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  fluttertoast: ^8.2.4
  cloud_firestore: ^4.13.5
#  flutx: ^0.2.0-rc.1
#  flutx: ^0.1.2

#module:
#  androidX: true

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:

    # Map Styles
    - assets/map/

    # Profiles
    - assets/images/profile/

    # Brand
    - assets/brand/

    # Event
    - assets/images/apps/event/
    - assets/images/event/

    # Avatars
    - assets/images/profile/

    ###################---------------------- Full Apps -------------------------#################

    # Month backgrounds
    - assets/images/month_background/

    # Languages
    - assets/lang/

    # Icons
    - assets/icons/

    # Other
    - assets/other/
