// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEBTzMQ0hORtv8g8KwFFq2FpLh1QAergk',
    appId: '1:1030896701175:web:769f69fb96153acb2bcdf2',
    messagingSenderId: '1030896701175',
    projectId: 'yoven-b885c',
    authDomain: 'yoven-b885c.firebaseapp.com',
    storageBucket: 'yoven-b885c.appspot.com',
    measurementId: 'G-VDL86GVJZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLKybw_SGRYxv7UlfGC_PaGV_1HtPFZV8',
    appId: '1:1030896701175:android:497f8d7bc861e1282bcdf2',
    messagingSenderId: '1030896701175',
    projectId: 'yoven-b885c',
    storageBucket: 'yoven-b885c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpi_nuae0GiTvVBjw-OADryxAjeAoCgHs',
    appId: '1:1030896701175:ios:c4a3679f0f0de41f2bcdf2',
    messagingSenderId: '1030896701175',
    projectId: 'yoven-b885c',
    storageBucket: 'yoven-b885c.appspot.com',
    iosBundleId: 'com.example.yoven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpi_nuae0GiTvVBjw-OADryxAjeAoCgHs',
    appId: '1:1030896701175:ios:fbc0e0e8bd8aa29b2bcdf2',
    messagingSenderId: '1030896701175',
    projectId: 'yoven-b885c',
    storageBucket: 'yoven-b885c.appspot.com',
    iosBundleId: 'com.example.yoven.RunnerTests',
  );
}
